CREATE TABLE "VP2"."DATA_ARCH" 
   (	"ID" NUMBER(*,0), 
	"OUTTEMP" NUMBER, 
	"HI_OUTTEMP" NUMBER, 
	"LO_OUTTEMP" NUMBER, 
	"RAIN" NUMBER, 
	"RAIN_RATE" NUMBER, 
	"BAR" NUMBER, 
	"OUTHUM" NUMBER, 
	"AVG_WSPEED" NUMBER, 
	"HI_WSPEED" NUMBER, 
	"DIR_HI_WSPEED" VARCHAR2(3 BYTE), 
	"AVG_WDIR" VARCHAR2(3 BYTE), 
	"TIME_ID" DATE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "VP2"."DATA_CURR" 
   (	"CURR_DATE" NUMBER, 
	"WINDDIR" VARCHAR2(3 BYTE), 
	"WINDSPEED" NUMBER, 
	"INTEMP" NUMBER, 
	"BAR_TREND" NUMBER, 
	"INHUM" NUMBER, 
	"AVG_WSPEED" NUMBER, 
	"FORECASTICON" NUMBER, 
	"OUTTEMP" NUMBER, 
	"DAYRAIN" NUMBER, 
	"STORMRAIN" NUMBER, 
	"OUTHUM" NUMBER, 
	"STORMSTART" NUMBER, 
	"RAIN_RATE" NUMBER, 
	"BAR" NUMBER, 
	"MONRAIN" NUMBER, 
	"YEARRAIN" NUMBER, 
	"FORECASTRULE" NUMBER, 
	"WINDDIR_DEG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
